name: salman_tahir
favicon: null
layout_spectrum: 0.7690086252987385
typography_spectrum: 0.10711479815654457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.25054212054237723
  lightness: 0.15852893167175353
  saturation: 0.24871562980115414
  rhythmicContrast: 0.15876140794716775
purpose: []
