name: salman_tahir
favicon: null
layout_spectrum: 0.74525
typography_spectrum: 0.25349
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfd1ea'
    - '#121818'
    - '#2c5183'
    - '#632c25'
    - '#e3707e'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
